name: CI
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        node-version:
          [
            '06',
            '07',
            '08',
            '09',
            '10',
            '11',
            '12',
            '13',
            '14',
            '15',
            '16',
            '17',
            '18',
            '19',
            '20',
            '21',
          ]
    name: 🔬 Node ${{ matrix.node-version }}
    steps:
      - name: ➕ Actions - Checkout
        uses: actions/checkout@v4

      - name: ➕ Actions - Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: ➕ Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: 📦 Installing Dependencies
        run: npm ci

      - name: 🤹🏻‍♀️ Building the Project
        run: npm run build

      - name: 🔬 Node ${{ matrix.node-version }}
        run: FILTER=${{ matrix.node-version }} npm run test:ci
